# Generated by Django 5.1 on 2024-08-20 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expensehistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('expense_type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.currentbalance')),
            ],
        ),
    ]
